config/routes.rb
Rails.application.routes.draw do
  get 'powerball/index'
  get 'result' => 'powerball#pick_your_ball'
  root 'powerball#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
    
    def game
        
        dice=[1,2,3,4,5,6]
        @dice1 = rand(0..5)
        @dice2 = rand(0..5)
        @dice_img1 = 'dice'+dice[@dice1].to_s
        @dice_img2 = 'dice'+dice[@dice2].to_s
        
        if @dice1 > @dice2
            @right='win'
            @left='lose'

        elsif @dice1 < @dice2
            @left='win'
            @right='lose'

        else
            return
        end
    end
    
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	characters1 = { 
  					"성실함": "handsome",
  					"고약함": "handsome",
  					"나약함": "handsome",
  					"비겁합": "handsome",
  					"섬세함": "handsome",
  					"야비함": "handsome",
  					"근면함": "handsome",
  					"느긋함": "handsome"
				}
		@choose1 = characters1.keys.sample(1)[0]

	characters2 = { 
  					"가인": "handsome",
  					"이쁨": "handsome",
  					"존예": "handsome",
  					"존잘": "handsome",
  					"미남": "handsome",
  					"미녀": "handsome",
  					"미인": "handsome",
  					"미모": "handsome"
				}
		@choose2 = characters2.keys.sample(1)[0]

	characters3 = { 
  					"초콜릿복근": "handsome",
  					"11자 복근": "handsome",
  					"갑빠": "handsome",
  					"애플힘": "handsome",
  					"화난엉덩이": "handsome",
  					"성난팔뚝": "handsome",
  					"강철허벅지": "handsome",
  					"이뚜빡끈": "handsome"
				}
		@choose3 = characters3.keys.sample(1)[0]
  end
end

app/controllers/powerball_controller.rb
class PowerballController < ApplicationController
	def index
	end

	def pick_your_ball
		#당첨볼
		drw_normalball = Array.new
		loop do
		  drw_normalball = (1..69).to_a.sample(5).sort
		  break if drw_normalball.uniq.size == 5
		end

		drw_powerball = (1..26).to_a.sample(1)

		#구입볼
		pick_normalball = Array.new
		loop do
			pick_normalball = (1..69).to_a.sample(5).sort
			break if pick_normalball.uniq.size == 5
		end

		pick_powerball = (1..26).to_a.sample(1)


		#당첨확인
		result = ""
		count_correct_num =""
		prize = 0
 		if (drw_normalball == pick_normalball) && (drw_powerball == pick_powerball)
 		    result = "JACKPOT"
 		    count_correct_num = 6
 		    prize = "누적된 상금"
 		elsif (drw_normalball & pick_normalball).size == 5
 		    result = "2등!"
 		    count_correct_num = 5
 		    prize = 1000000
 		elsif ((drw_normalball & pick_normalball).size == 4) && (drw_powerball == pick_powerball)
 		    result = "3등"
 		    count_correct_num = 5
 		    prize = 10000
 		elsif (drw_normalball & pick_normalball).size == 4
 		    result = "4등"
 		    count_correct_num = 4
 		    prize = 100
 		elsif ((drw_normalball & pick_normalball).size == 3) && (drw_powerball == pick_powerball)
 		    result = "5등"
 		    count_correct_num = 4
 		    prize = 100
 		elsif (drw_normalball & pick_normalball).size == 3
 		    result = "6등"
 		    count_correct_num = 3
 		    prize = 7
 		elsif ((drw_normalball & pick_normalball).size == 2) && (drw_powerball == pick_powerball)
 		    result = "7등"
 		    count_correct_num = 3
 		    prize = 7
 		elsif ((drw_normalball & pick_normalball).size == 1) && (drw_powerball == pick_powerball)
 			result = "8등"
 			count_correct_num = 2
 			prize = 4
 		elsif drw_powerball == pick_powerball
 			result = "9등"
 			count_correct_num = 1
 			prize = 4
 		else
 			result = "꽝"
 			count_correct_num = 0
 			prize = 0
 		end

        #옵션볼 배당률 & 상금계산기
		magnification = ""
		money = 0
		option_ball = (1..43).to_a.sample(1)
		if option_ball == 1
			magnification = "x10"
			money = (prize*10)
		elsif  (option_ball.first <= 3) && (option_ball.first >= 2)
			magnification = "x5"
			money = (prize*5)
		elsif (option_ball.first <= 6) && (option_ball.first >= 4)
			magnification = "x4"
			money = (prize*4)
		elsif (option_ball.first <= 19) && (option_ball.first >= 7)
			magnification = "x3"
			money = (prize*3)
		else
			magnification = "x2"
			money = (prize*2)
		end
        
 		#맞은번호 확인
 		correct_normalball = drw_normalball & pick_normalball
 		correct_powerball = drw_powerball & pick_powerball 
 		
		#인스턴스 변수 저장
		@drw_normalball = drw_normalball #당첨 일반볼
		@drw_powerball = drw_powerball #당첨 파워볼
		@pick_normalball = pick_normalball #뽑은 일반볼
		@pick_powerball = pick_powerball #뽑은 파워볼
		@magnification = magnification #당첨 배율
		@correct_normalball = correct_normalball #맞은 일반볼 배열
		@correct_powerball = correct_powerball #맞은 파워볼 배열
		@count_correct_num = count_correct_num #맞은 볼 갯수
		@result = result
		@money = money
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/powerball_helper.rb
module PowerballHelper
end

app/views/game/game.html.erb
<div class="title">
    <p>DICE GAME</p>
</div>

<div class="bottom">
    <div class="dice">
        <div class="col-md-1"></div>
        <div class="col-md-5">
            <p><%= @dice1+1 %></p>
            <img src="<%= image_url(@dice_img1)%>">
        </div>
        <div class="col-md-5">
            <p><%= @dice2+1 %></p>
            <img src="<%= image_url(@dice_img2)%>">
        <div class="col-md-1"></div>
    </div>
</div>


<div class="result">
    <div class="col-md-1"></div>
    <div class="col-md-5"> 
        <img id="face1" src="<%= image_url(@right)%>" >
    </div>
    <div class="col-md-5"> 
        <img id="face2" src="<%= image_url(@left)%>">
    </div>
    <div class="col-md-1"></div>
</div>

app/views/home/game.html.erb
   <!-- game -->
    <section class="game">
       <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                     <h2 class="sectiontitle">신이 나를 만들 때</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <img src= "/assets/case3.jpg" align="center" id="centerimage">
            </div>
        </div>
    </div>
  </section>

app/views/home/index.html.erb
<div class="container-fluid" style="background-color:#F44336;color:#fff;height:200px;">
  <h1>만약 shin이 나를 만든다면...?</h1>
  <h3>shin은 과연 나에게 무엇을??</h3>
  <p><h3>두근두근</h3></p>
  
</div>

<nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="197">
  <ul class="nav navbar-nav">
    <li class="active"><a href="#">다시만들기!</a></li> 
  </ul>
</nav>


<table>
	<td>
		<h2 class="text1"><%= @choose1 %>(을)를 한번 뱉고</h2>
	</td>
	<td>
		<h2 class="text2"><%= @choose2 %>(을)를 푼다음</h2>
	</td>
	<td>
		<h2 class="text3"><%= @choose3 %>(을)를쏟아내자!</h2>
	</td>
</table>	
	
<img class="image"src="/assets/sms.png">

app/views/home/result.html.erb
<div class = "container">
  <center>
   <div class = "row"> <div class = "title">
   <span class="one">  신</span>이 <span class="one">나</span>를 만들때
   </span></div>
   <div class = "row">
       <div class = "col-md-4">
           <h1 class = "godtext"><span class = "instance1"><%="#{@first_god}"%></span>을</br>우선 조금 넣고..</h1></br></br>
           <img class = "god" src = "/assets/god1.png"/>
       </div>
       <div class = "col-md-4">
           <h1 class = "godtext"><span class = "instance2"><%="#{@second_god}"%></span>은</br>두스푼 넣고..</h1></br></br>
           <img class = "god" src = "/assets/god2.png"/>
       </div>
       <div class = "col-md-4">
           <h1 class = "godtext"><span class = "instance3"><%="#{@third_god}"%></span>도 조금</br>넣으어어어ㅓ</br>69통을 넣어버림ㅋ</h1>
           <img class = "god" src = "/assets/god3.png"/>
       </div>
   </div>
  </center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/powerball/index.html.erb
<div class="jumbotron">    
    <div class="container">
        <h1>JACKPOT CHECKER</h1>
        <p>일확천금의 기회 POWER BALL 당신의 행운을 확인하세요!</p>
        <p>
            <a class="btn btn-primary btn-lg" href="result" role="button">결과 보러가기</a>
        </p>
    </div>
</div>

app/views/powerball/pick_your_ball.html.erb
<div class="container">
    <h1>일확천금의 기회 POWERBALL! 당신의 결과는?</h1>
    <p><%= "당첨 일반볼 번호는 #{@drw_normalball} 이고, 파워볼 번호는 #{@drw_powerball} 입니다. 배율은 #{@magnification}!!" %></p>
	<!-- 밑에 추첨한 로또 번호, 겹치는 번호, 결과를 출력해주세요.-->
    <p><%= "당신이 선택 한 일반볼은 #{@pick_normalball}!, 파워볼은 #{@pick_powerball} 맞은 번호는 일반볼 #{@correct_normalball}, 파워볼 #{@correct_powerball}, 갯수는 #{@count_correct_num}! 당신의 결과는 #{@result} 입니다."%>
    <p><%= "당신이 받게될 금액은 #{@money}$입니다!" %></p>
</div>
<div class="container">
	<%= link_to "다시 뽑기?", result_path %>
</div>